apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  service.beta.kubernetes.io/azure-load-balancer-resource-group: ChatBoxKuberNetes
  service.beta.kubernetes.io/azure-pip-name: myAKSPublicIP
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer