apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    app: profile
    kind: chatbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - env:
            - name: DOTNET_ENVIRONMENT
              value: Production
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: trace
        name: profile-api
        image: martijnd95/chatbox-profileservice:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"