apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: ChatboxKubeResourcegroup
    service.beta.kubernetes.io/azure-pip-name: ChatboxPublicIP
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer